# Generated by Django 4.2.7 on 2025-12-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_app", "0002_alter_task_options_task_is_recurring_task_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Math", "Math"),
                    ("Science", "Science"),
                    ("History", "History"),
                    ("Literature", "Literature"),
                    ("Languages", "Languages"),
                    ("Programming", "Programming"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
